version: 1.0.{build}
image: Visual Studio 2022

# https://trac.ffmpeg.org/ticket/11538

environment:
  PATH: $(PATH);C:\msys64\mingw64\bin;C:\msys64\usr\bin;C:\msys64\opt\bin
  PKG_CONFIG_PATH: /c/dev/build/install;C/msys64/mingw64/lib/pkgconfig

clone_script:
  - git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - git checkout -qf %APPVEYOR_REPO_COMMIT%

install:
  - pacman -S --noconfirm --needed nasm yasm libgnutls-devel mingw-w64-x86_64-dav1d mingw-w64-x86_64-libxml2-2.0 mingw-w64-cross-gcc mingw-w64-x86_64-pkg-config

build_script:
  - build.bat
